### ISSUE TITLE
Typo in the README and repo description

### ISSUE THREAD

**Issue by toh995** [PortNumber53/github-actions#2]
The README and repo description has a typo (`github a ctions` instead of `github actions`)

**Comment by PortNumber53** [comment]
are you following my typos?  😆

**Comment by PortNumber53** [comment]
Fixed here!
https://github.com/PortNumber53/github-actions/commit/7d4060c482af785c99c11e14062c27fc3dedbe72

**Comment by toh995** [comment]
Old habits die hard @PortNumber53 haha

Nice fix!
